### ISSUE TITLE
Possible addition

### ISSUE THREAD

**Issue by springcoil** [mvanderkroon/cobr#1]
Hey man, just a possible addition. 
I'd recommend for the database and csv handling tooling looking into 
http://csvkit.readthedocs.org/en/latest/

**Comment by mvanderkroon** [comment]
thanks, very useful!

**Comment by springcoil** [comment]
Hi,
Do you need me to make a PR?


On Fri, Mar 13, 2015 at 8:54 AM, Matthijs van der Kroon <
notifications@github.com> wrote:

> thanks, very useful!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mvanderkroon/cobr/issues/1#issuecomment-78855325>.
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by mvanderkroon** [comment]
I used your great suggestion to implement a POST end-point in the HttpODBC API (https://github.com/mvanderkroon/cobr/blob/master/api/HttpODBC.py); basically now accepting csv files and automatically importing them into your database. (A GET request to the same address converts the database table to a csv). Feel free to make any PR if you like the framework!

**Comment by springcoil** [comment]
I think a PR would be too much though you've done probably the best part of
it. Maybe though I'll add csvstat or something because statistics of the
csv thing are needed.

On Wed, Mar 18, 2015 at 9:31 AM, Matthijs van der Kroon <
notifications@github.com> wrote:

> Closed #1 <https://github.com/mvanderkroon/cobr/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mvanderkroon/cobr/issues/1#event-257851412>.
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com
